"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
from corsheaders.defaults import default_headers

# Load environment variables from .env file
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-*+c@c-5ao-e+&jmtm&@(enzo@9x9qft)bmj$%8gg_&$5zu$4o5"
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-*+c@c-5ao-e+&jmtm&@(enzo@9x9qft)bmj$%8gg_&$5zu$4o5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    ".vercel.app",
    "localhost",
    "127.0.0.1"
]


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # thirdparty app
    "rest_framework",
    "allauth",  # Required for social auth
    # "allauth.account",  # Required for social auth
    "auth_kit",
    "drf_yasg",
    # App
    "users.apps.UsersConfig",
    "schools.apps.SchoolsConfig",
    "staff.apps.StaffConfig",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


#    "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PGDATABASE', 'neondb'),
        'USER': os.getenv('PGUSER', 'neondb_owner'),
        'PASSWORD': os.getenv('PGPASSWORD', 'npg_yC9Gq0RoFnpi'),
        'HOST': os.getenv('PGHOST', 'ep-solitary-cloud-ah44tvy5-pooler.c-3.us-east-1.aws.neon.tech'),
        'PORT': '5432',  # Default PostgreSQL port
        'OPTIONS': {
            'sslmode': 'require',  # Required for Neon.tech
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "users.User"


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        # "rest_framework.permissions.IsAuthenticated",  # or "rest_framework.permissions.AllowAny" for public access
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "auth_kit.authentication.JWTCookieAuthentication",
        # "rest_framework.authentication.SessionAuthentication",  # Add this for Swagger
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


AUTH_KIT = {
    # ===================================================================
    # CORE AUTHENTICATION SETTINGS
    # ===================================================================
    "AUTH_TYPE": "jwt",  # 'jwt', 'token', or 'custom'
    "USE_AUTH_COOKIE": True,  # Enable cookie-based authentication
    "SESSION_LOGIN": False,  # Enable Django session login
    "ALLOW_LOGIN_REDIRECT": False,  # Allow login redirects
    # ===================================================================
    # COOKIE CONFIGURATION
    # ===================================================================
    "AUTH_COOKIE_SECURE": os.getenv("AUTH_COOKIE_SECURE", "False").lower() == "true",  # Require HTTPS for cookies
    "AUTH_COOKIE_HTTPONLY": True,  # Prevent JavaScript access
    "AUTH_COOKIE_SAMESITE": "Lax",  # 'Lax', 'Strict', or 'None'
    "AUTH_COOKIE_DOMAIN": None,  # Cookie domain
    # ===================================================================
    # JWT AUTHENTICATION SETTINGS
    # ===================================================================
    "AUTH_JWT_COOKIE_NAME": "auth-jwt",
    "AUTH_JWT_COOKIE_PATH": "/",
    "AUTH_JWT_REFRESH_COOKIE_NAME": "auth-refresh-jwt",
    "AUTH_JWT_REFRESH_COOKIE_PATH": "/",
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # React / Next.js default
    "http://localhost:8000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# settings.py



CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-device-id",  # <--- Add your custom header here
]