# Generated by Django 5.2.7 on 2025-11-18 17:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('address_line', models.CharField(help_text='Street address, P.O. box', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(help_text='State/Province/Region', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='CM', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['country', 'state_province', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(help_text='Name of the campus', max_length=255)),
                ('code', models.CharField(help_text='Unique code for the campus (e.g., MAIN, CAMPUS_A)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone', models.CharField(blank=True, help_text='Main contact number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Main contact email', max_length=254, null=True)),
                ('is_main_campus', models.BooleanField(default=False, help_text='Is this the main campus of the school?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, help_text='Custom title for the role (if not covered by role type)', max_length=100, null=True)),
                ('school_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('high_school', 'High School'), ('college', 'College'), ('university', 'University'), ('other', 'Other')], default='primary', help_text='The school type this role is associated with (if applicable)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Short name or abbreviation', max_length=50, null=True)),
                ('school_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('high_school', 'High School'), ('college', 'College'), ('university', 'University'), ('other', 'Other')], default='primary', help_text='Type of school (e.g., Primary, Secondary, High School)', max_length=50, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
    ]
