# Generated by Django 5.2.7 on 2025-11-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='abbreviation',
            field=models.CharField(default=1, max_length=50, verbose_name='abbreviation'),
            preserve_default=False,
        ),
    ]
